# TrajectoryPlannerROS:
#   max_vel_x: 0.3
#   min_vel_x: 0.1
#   max_vel_theta: 0.25
#   min_in_place_vel_theta: 0.4

#   acc_lim_theta: 0.25
#   acc_lim_x: 2.5
#   acc_lim_Y: 2.5

#   holonomic_robot: false

#   meter_scoring: true

#   xy_goal_tolerance: 0.15
#   yaw_goal_tolerance: 0.15

  #####
# TrajectoryPlannerROS:
#   max_vel_x: 0.5
#   min_vel_x: 0.1
#   max_vel_theta: 0.25
#   min_in_place_vel_theta: 0.4

#   acc_lim_theta: 0.25
#   acc_lim_x: 2.5
#   acc_lim_Y: 2.5

#   holonomic_robot: false

#   meter_scoring: true

#   xy_goal_tolerance: 0.1
#   yaw_goal_tolerance: 0.15

# turtlebot
controller_frequency: 10.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
   max_vel_x: 0.3
   min_vel_x: -0.0
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_vel_theta: 0.25
   min_vel_theta: -0.25
   min_in_place_vel_theta: 0.5
   escape_vel: -0.1
   acc_lim_x: 3.0
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 5.0

   holonomic_robot: false
   yaw_goal_tolerance: 0.15 # about 6 degrees
   xy_goal_tolerance: 0.15  # 10 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.8
   gdist_scale: 0.3
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.1
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 1.0
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 8
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 20
   dwa: true
   simple_attractor: false