# local_costmap:
#   # global_frame: odom
#   # robot_base_frame: base_link
#   update_frequency: 10.0
#   publish_frequency: 10.0
#   transform_tolerance: 0.5
#   static_map: false
#   rolling_window: true
#   width: 3
#   height: 3
#   origin_x: -1.5
#   origin_y: -1.5
#   resolution: 0.05

  ### ros wiki ###
  # global_frame: odom
  # robot_base_frame: base_link
  # update_frequency: 5.0
  # publish_frequency: 2.0
  # static_map: false
  # rolling_window: true
  # width: 6.0
  # height: 6.0
  # origin_x: -3.0
  # origin_y: -3.0
  # resolution: 0.05

  ###
# local_costmap:
#   update_frequency: 10.0
#   publish_frequency: 10.0
#   transform_tolerance: 5
#   static_map: false
#   rolling_window: true
#   width: 1
#   height: 1
#   origin_x: -0.5
#   origin_y: -0.5
#   resolution: 0.1

# turtlebot
local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   update_frequency: 10.0
   publish_frequency: 2.0
   transform_tolerance: 1.0
   static_map: false
   rolling_window: true
   width: 10.0
   height: 10.0
   resolution: 0.05
   map_type: costmap